owner: appany
repo: AppAny.StatusPage

sites:
  - name: AppAny Egrn
    url: https://egrn.appany.ru
    maxResponseTime: 1000
    expectedStatusCodes: [200]
  - name: AppAny Template
    url: https://template.staging.appany.ru

status-website:
  cname: status.appany.ru
  logoUrl: https://raw.githubusercontent.com/appany/AppAny.StatusPage/master/assets/logo.png
  name: AppAny | StatusPage
  # introTitle:
  # introMessage:
  navbar:
    - title: Status
      href: /

assignees:
  - sergeyshaykhullin

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
